default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: secret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quotes

test:
  <<: *default
  database: quotes_test
